### ISSUE TITLE
No annotation after close inkscape/quit

### ISSUE THREAD

**Issue by mizhozan** [oxplot/pdfrankenstein#10]
Hi, 

First of all thanks for the app. I seems to be a great idea to offload the editing by inkscape and have all its power while the app manage the rest though I couldn't achieve this yet. 

I did this workflow:
1. Open a PDF with PDFrankenstein and subsequently the inkscape opens and I did my annotations
2. I save and close the document inside inkscape and came back to PDFrankenstein, nothing there. The whole app is inactive.
3. I did quit inkscape, automatically PDFrankenstein also quits 
4. As I open the pdf there is no annotation there.

Have I missed something here?

**Comment by oxplot** [comment]
That's not good! Can you run the app in the terminal and see if you get any errors in there that can help. Also, can you paste the output of `uname -r` and `inkscape --version`.

**Comment by mizhozan** [comment]
Sorry for late response I loose interest for a while in the solution, however I just install the newer version and did the same this time and everything worked seamlessly. Thanks for the great app. 

* `uname -r`: 5.18.14
* `inkscape --version`: Inkscape 1.2.1

**Comment by oxplot** [comment]
> Sorry for late response I loose interest for a while in the solution, however I just install the newer version and did the same this time and everything worked seamlessly. Thanks for the great app.
> 
> * `uname -r`: 5.18.14
> * `inkscape --version`: Inkscape 1.2.1

No problems. Thanks for the update.
