### ISSUE TITLE
Build is failing

### ISSUE THREAD

**Issue by Faaaabian** [oxplot/pdfrankenstein#17]
Hello @oxplot !
while I was searching for a tool to properly write into pdf files with my stylus, I found your project and wanted to try it out. Unfortunately, the build is failing when I'm trying to install it via yay (I'm on ArchLinux). So I decided to build it via the source as you noted in the README.md, but I get the same error, which looks like this:

![image](https://user-images.githubusercontent.com/51411388/225954058-2189bb97-532c-401c-9a54-7f6c9c469c85.png)

Please fix this error! I will try to research it also - if I find it, I will make a pull request, but I have to note, that I have not worked with Go yet, so I would appreciate if you would also look into this error.

Also, maybe set the "-parallel" flag in the PKGBUILD file, friendly reminder from a slow laptop user (if possible only of course)

Have a nice day :D
Fabian

**Comment by oxplot** [comment]
Thanks for the report.

In the meantime, you can use the pre-built binaries: https://github.com/oxplot/pdfrankenstein/releases/tag/v0.9.3

**Comment by oxplot** [comment]
@Faaaabian those are not errors — just warnings. Is your build actually failing or is it just taking a long time? Because it *does* take a long time.

**Comment by Faaaabian** [comment]
Oh this is also possible. I'm gonna try leaving it for longer - I was just irritated by my terminal not reacting in any way
