### ISSUE TITLE
Unknown option --pages=4

### ISSUE THREAD

**Issue by smoehrle** [oxplot/pdfrankenstein#18]
Just cloned, build and installed the latest version (v0.9.11). I can open PDF files, but when I click on a page, I receive the following:

"Cannot annotate file: failed to convert page 3 of '/tmp/pdfrankenstein-1174498170/src.pdf' to svg: Unknown option --pages=4

Context:
Ubuntu 23.04
Inkscape 1.2.2 (b0a8486541, 2022-12-01)
poppler-utils/lunar-updates,lunar-security,now 22.12.0-2ubuntu1.1 amd64 [installed]
qpdf version 11.3.0

I suspect the problem is missing dependencies, but at the moment I'm not able to dig into that

**Comment by oxplot** [comment]
This is already fixed in latest version.

**Comment by oxplot** [comment]
Latest Inkscape 1.3 changes the flags for exporting. You can use an older version of the app [v0.9.3](https://github.com/oxplot/pdfrankenstein/releases/tag/v0.9.3) for now. I'll make an update to support both inkscape versions.

**Comment by oxplot** [comment]
https://github.com/oxplot/pdfrankenstein/releases/tag/v0.9.12 fixes this.
