### ISSUE TITLE
Add cmdline parameter to open PDF

### ISSUE THREAD

**Issue by shibmaster** [oxplot/pdfrankenstein#7]
Very nice Project! I think it is somewhat tedious to navigate through the folders inside the app, so I wonder how much effort it is to open a PDF directly when starting the program from shell?

Thanks and keep it up!

**Comment by oxplot** [comment]
Oh ye — that's actually quite easy and I'll do it soon. Thanks for the report.

**Comment by oxplot** [comment]
@shibmaster available in release https://github.com/oxplot/pdfrankenstein/releases/tag/v0.4
